FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    bash \
    binutils \
    wget \
    git \
    vim \
    debootstrap \
    libssl-dev bc qemu-user-static gcc-aarch64-linux-gnu kmod bison flex device-tree-compiler fdisk parted udev dosfstools liblz-dev uuid-dev libgnutls28-dev coreutils


